### ISSUE TITLE
protobuf requirement package conflicts

### ISSUE THREAD

**Issue by lynnssi** [milvus-io/milvus-model#15]
milvus-model==0.2.0 requires protobuf==3.2.0. This conflicts with a package that I need for testing in a cloud environment: that requires "protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5,". 

pymilvus==2.4.0 depends on protobuf>=3.2.0 and the next version of pymilvus may depend on protobuf==4.25.2, both of which are perfectly compatible.

Could milvus-model's protobuf dependency match the pymilvus dependency exactly?

https://github.com/milvus-io/milvus-model/blob/8202e8fe864f902487fb28b0e4b29a411bfb70b6/pyproject.toml#L28

**Comment by wxywb** [comment]
The reason for this protobuf requirement is that we are using Hugging Face's transformer for some models, and it needs protobuf version 3.20.2 or lower.
https://github.com/huggingface/transformers/blob/a8eb4f79f946c5785f0e91b356ce328248916a05/setup.py#L141
3.20.2 seems a current feasible solution. We will delve deeper into this.

**Comment by wxywb** [comment]
the specific version dependency is removed.
