### ISSUE TITLE
BGEM3EmbeddingFunction Encoding Error

### ISSUE THREAD

**Issue by danielruales** [milvus-io/milvus-model#52]
I'm getting an embedding error using the Python code directly from the milvus documentation on this page: https://milvus.io/docs/hybrid_search_with_milvus.md

Error:
TypeError: M3Embedder.encode() missing 1 required positional argument: 'sentences'

Code:
import pandas as pd

file_path = "quora_duplicate_questions.tsv"
df = pd.read_csv(file_path, sep="\t")
questions = set()
for _, row in df.iterrows():
    obj = row.to_dict()
    questions.add(obj["question1"][:512])
    questions.add(obj["question2"][:512])
    if len(questions) > 500:  # Skip this if you want to use the full dataset
        break

docs = list(questions)

print(docs[0])

from milvus_model.hybrid import BGEM3EmbeddingFunction

ef = BGEM3EmbeddingFunction(use_fp16=False, device="cpu")
dense_dim = ef.dim["dense"]

docs_embeddings = ef(docs)

**Comment by wxywb** [comment]
Could you tell me the version of milvus-model and FlagEmbedding you currently using?

**Comment by danielruales** [comment]
FlagEmbedding                1.3.3
milvus-model                 0.2.10

**Comment by wxywb** [comment]
I have found the reason, thanks for pointing out, I will released a new version today to fix it.
