### ISSUE TITLE
Default behavior is for embedding to fail when greater than maximum input

### ISSUE THREAD

**Issue by stefanwebb** [milvus-io/milvus-model#57]
When your tokenized input is greater than the model can accept, the current behavior is for an exception to be thrown.

The difficulty is, however, that you can't fix this by either truncating your inputs or setting a parameter within milvus-model.

What do you think about adding a `truncation=True` parameter to `.encode_plus` in this line:

https://github.com/milvus-io/milvus-model/blob/main/milvus_model/dense/onnx.py#L35

?

**Comment by wxywb** [comment]
This makes sense, I will add this.
